using System.Collections;
using UnityEngine;


public class Boss : MonoBehaviour

{
    
    private Coroutine bossLoop;
    private int lastSkill1 = -1; // Í∞ÄÏû• ÏµúÍ∑º
    private int lastSkill2 = -1;
    private int bossfightEnterCount = 0;
    private int bossfightRunCount = 0;
    private bool phase2Start = false;
    private bool isDoingPattern = false;
    public GameObject tentacle;
    public GameObject verticle_tentacle; //1111
    public GameObject Egg;
    public GameObject All_attack;
    public GameObject Ready_motion;
    public BossHPUI bossHPUI;
    private float lastHP = -1f;

    

    IEnumerator Start()
    {
        StartBossLoop();

        yield return null; // Ìïú ÌîÑÎ†àÏûÑ ÎåÄÍ∏∞(Ï¥àÍ∏∞Ìôî ÏàúÏÑú ÏïàÏ†ï)
        if (bossHPUI != null && GameManager.Instance != null)
            bossHPUI.Init(GameManager.Instance.bossMaxHP);
    }


    private void StartBossLoop()
    {
        if (bossLoop != null) return; //  Ïù¥ÎØ∏ ÎèåÍ≥† ÏûàÏúºÎ©¥ ÏãúÏûë Í∏àÏßÄ
        bossLoop = StartCoroutine(Bossfight());
    }


    // Update is called once per frame
    void Update()
    {
        {
            if (bossHPUI == null || GameManager.Instance == null) return;
            bossHPUI.SetHP(GameManager.Instance.bossHP);
        }
    }

    int GetNextSkillNoLast2()
    {
        int min = phase2Start ? 2 : 0;
        int max = phase2Start ? 7 : 3; 

        int range = max - min;

        // Î≤îÏúÑÍ∞Ä 3Í∞ú ÎØ∏ÎßåÏù¥Î©¥ "ÏµúÍ∑º 2Í∞ú Í∏àÏßÄ"Î•º ÏôÑÎ≤ΩÌûà ÎßåÏ°±Ìï† Ïàò ÏóÜÏùå
        // (Ïòà: ÏÑ†ÌÉùÏßÄÍ∞Ä 2Í∞úÏù∏Îç∞ ÏµúÍ∑º 2Í∞úÎ•º Í∏àÏßÄÌïòÎ©¥ ÎÇ®Îäî Í≤å 0Í∞ú)
        // Í∑∏ÎûòÏÑú Ïù¥ Í≤ΩÏö∞Îäî "ÏµúÍ∑º 1Í∞úÎßå Í∏àÏßÄ"Î°ú ÏûêÎèô ÏôÑÌôî
        bool banLast2 = range >= 3;

        int next = Random.Range(min, max);

        if (banLast2)
        {
            while (next == lastSkill1 || next == lastSkill2)
                next = Random.Range(min, max);
        }
        else if (range >= 2)
        {
            while (next == lastSkill1)
                next = Random.Range(min, max);
        }

        // Í∏∞Î°ù ÏóÖÎç∞Ïù¥Ìä∏
        lastSkill2 = lastSkill1;
        lastSkill1 = next;

        return next;
    }

    IEnumerator Bossfight()
    {
        Debug.Log("[Boss] Bossfight START");

        // Ï≤´ Ïä§ÌÇ¨ Ï¥àÍ∏∞Ìôî
        GameManager.Instance.skill = GetNextSkillNoLast2();

        while (true)
        {
            //  Phase2 ÏßÑÏûÖ Ï≤òÎ¶¨ (Îã® 1Î≤à)
            if (!phase2Start && GameManager.Instance.bossHP <= 60)
            {
                phase2Start = true;

                // ÏµúÍ∑º Í∏∞Î°ù Ï¥àÍ∏∞Ìôî (Í∂åÏû•)
                lastSkill1 = -1;
                lastSkill2 = -1;

                // Ï†ÑÏ≤¥ Í≥µÍ≤© ÎèôÏïà ÏôÑÏ†Ñ Ï†ïÏßÄ
                yield return StartCoroutine(All_attack_on());
                yield return new WaitForSeconds(3f);
            }

            // üü¢ Ìå®ÌÑ¥ 1Ìöå Ïã§Ìñâ
            yield return StartCoroutine(DoPattern(GameManager.Instance.skill));

            // üü° Îã§Ïùå Ïä§ÌÇ¨ ÏÑ†ÌÉù (ÏµúÍ∑º 2Í∞ú Í∏àÏßÄ)
            GameManager.Instance.skill = GetNextSkillNoLast2();

            //  Ìå®ÌÑ¥ Í∞Ñ Ïø®ÌÉÄÏûÑ
            yield return new WaitForSeconds(4f);
        }
    }

    IEnumerator DoPattern(int skill) {

    switch (skill)
        {
            case 0:
            {
                Vector2 attackPos = new Vector2(0f, 0f); // tentacle_skillÏù¥ Ïì∞Îäî ÏúÑÏπòÏôÄ ÎèôÏùº
                Vector2 size = GetColliderSize(tentacle);
                float warnTime = 0.8f;

                yield return StartCoroutine(ShowDangerRect(attackPos, size, warnTime));
                tentacle_skill(true);
                break;
            }



            case 1:
            {
                Vector2 attackPos = GameManager.Instance.player.transform.position + new Vector3(0, -2, 0);

                // Ï¥âÏàò ÌûàÌä∏Î∞ïÏä§ Í∏∞Ï§Ä ÌÅ¨Í∏∞ ÏñªÍ∏∞
                Collider2D col = verticle_tentacle.GetComponent<Collider2D>();
                Vector2 size = col.bounds.size;

                // ÏúÑÌóò ÌëúÏãú
                yield return StartCoroutine(
                    ShowDangerRect(attackPos, size, 1f)
                );

                // Ïã§Ï†ú Í≥µÍ≤©
                vertical_tentacle_skill(2f);
                break;
            }


            case 2:
            {
                float warnTime = 0.6f;
                Vector2 eggSize = GetColliderSize(Egg);

                for (int i = 0; i < 4; i++)
                {
                    // ‚úÖ Ïã§Ï†ú ÏÉùÏÑ±Îê† Ï¢åÌëúÎ•º ÎØ∏Î¶¨ Í≤∞Ï†ï
                    Vector2 spawnPos = new Vector2(
                        Random.Range(transform.position.x, -8),
                        GameManager.Instance.player.transform.position.y + 0f
                    );

                    // ÏòàÍ≥†
                    yield return StartCoroutine(ShowDangerRect(spawnPos, eggSize, warnTime));

                    // Ïã§Ï†ú ÏÉùÏÑ±(Ï¢åÌëúÎ•º ÏßÅÏ†ë ÎÑòÍ≤®ÏÑú ÏùºÏπò Î≥¥Ïû•)
                    Instantiate(Egg, spawnPos, Quaternion.identity);
                }
                break;
            }

            case 3:
            {
                Collider2D col = All_attack.GetComponent<Collider2D>();
                Vector2 pos = col.bounds.center;
                Vector2 size = col.bounds.size;

                yield return StartCoroutine(
                    ShowDangerRect(pos, size, 1.2f)
                );

                yield return StartCoroutine(All_attack_on());
                break;
            }

            

            case 4: // Egg_vertical
                vertical_tentacle_skill(3.5f);
                for (int i = 0; i < 6; i++) {
                    Egg_skill(20);
                }
                break;



            case 5:
            {
                float warnTime = 0.7f;

                // ÏÑ∏Î°ú Ï¥âÏàò 4Ìöå
                for (int i = 0; i < 4; i++)
                {
                    Vector2 pos = (Vector2)GameManager.Instance.player.transform.position + new Vector2(0f, -2f);
                    Vector2 size = GetColliderSize(verticle_tentacle) * 4f; // ÎÑ§ Ïä§ÏºÄÏùº Î∞òÏòÅ

                    yield return StartCoroutine(ShowDangerRect(pos, size, warnTime));
                    vertical_tentacle_skill(2f);

                    yield return new WaitForSeconds(0.2f); // Ìå®ÌÑ¥ ÌÖúÌè¨(ÏõêÌïòÎ©¥)
                }

                // ÎßàÏßÄÎßâ Ï¥âÏàò 1Ìöå
                Vector2 tpos = new Vector2(0f, 0f);
                Vector2 tsize = GetColliderSize(tentacle);

                yield return StartCoroutine(ShowDangerRect(tpos, tsize, 0.8f));
                tentacle_skill(true);

                break;
            }

        }
    
    }

    void tentacle_skill(bool a)
    {
         Instantiate(tentacle,new Vector3(0, 0f, 0), Quaternion.Euler(0, 0, 0));

            
       
        
    }

    void vertical_tentacle_skill(float a)
    { 
        var obj = Instantiate(
            verticle_tentacle, GameManager.Instance.player.transform.position + new Vector3(0, -2, 0), Quaternion.identity);

        obj.transform.localScale *= a;

        Destroy(obj, 1f);
    }

    void Egg_skill(float a)
    {
        Instantiate(Egg,
            new Vector3(Random.Range(transform.position.x, -8),
                GameManager.Instance.player.transform.position.y + a, 0), Quaternion.Euler(0, 0, 0));

    }

IEnumerator All_attack_on()
    {
        All_attack.SetActive(true);
        yield return new WaitForSeconds(1.1f);
        All_attack.GetComponent<Collider2D>().enabled = true;
        yield return new WaitForSeconds(0.9f);
        All_attack.GetComponent<Collider2D>().enabled = false;
        All_attack.SetActive(false);
    }
[SerializeField] private GameObject dangerRectPrefab;

IEnumerator ShowDangerRect(Vector2 pos, Vector2 size, float duration)
{
    GameObject danger = Instantiate(dangerRectPrefab, pos, Quaternion.identity);
    danger.transform.localScale = size;

    yield return new WaitForSeconds(duration);

    Destroy(danger);
}

Vector2 GetColliderSize(GameObject prefabOrObj)
{
    var col = prefabOrObj.GetComponentInChildren<Collider2D>(true);
    return col != null ? (Vector2)col.bounds.size : Vector2.one;
}


}